baseURL = '/'
languageCode = 'en-us'
title = '{{ .AppName }}'
enableGitInfo = true

[params]

    [params.docs]
        title = '{{ .AppName }}'
        darkMode = true
        repoURL = "https://github.com/twinsnes/cligen"

    [params.social]
        github = "twinsnes/cligen"

    [params.flexsearch]
        enavled = true

[menu]
[[menu.primary]]
    name = "Docs"
    url = "docs/"
    identifier = "docs"
    weight = 10

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false